# Generated by Django 2.1.3 on 2019-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_ans',
            field=models.BooleanField(default=False),
        ),
    ]
