# Generated by Django 2.1.3 on 2019-01-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20190110_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question'),
        ),
    ]
